name: Inkscape Windows Build & Release

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-windows.yml
    with:
      clean: false
      publish_release: true
    secrets: inherit
